## 0. 제출 정보
- 이름: 박재선
- GitHub ID: lilypark0930-lab
- 작성일: 2026.09.20
- 최종 제출 URL: https://github.com/lilypark0930-lab/llm-data-analysis-study/blob/main/chapter03/chapter03.ipynb

## 1. 데이터 로딩과 구조 확인
### 실행/결과
- 4개 CSV 로딩 여부: True
- 각 데이터 shape: 
customers (150, 6)
products (100, 4)
orders (300, 5)
order_items (764, 5)
- 주요 컬럼: ['customer_id', 'name', 'gender', 'age', 'city', 'signup_date']
- dtypes에서 주목한 컬럼: signup_date 

### Evidence
![데이터 구조 확인](images/step01_structure.png)

### 결과 관찰
직접 확인한 사실을 작성하세요.
- 데이터의 행과 열 개수 : 각 데이터별 행과 열의 개수를 shape을 통해 알 수 있다. 
- 실제 컬럼명 : 주요 컬럽을 알수 있다. 
- 눈에 띄는 값의 형태를 미리 알 수 있다.

### 나의 해석과 판단
분석 전에 특히 주의해야 할 데이터셋/컬럼과 이유를 작성하세요.
- signup_date 와 같이 날짜처럼 보이지만 문자열(str)로 읽힌 컬럼이 있다.

### 업무·분석적 의미
구조를 먼저 확인하지 않고 분석을 시작할 때 생길 수 있는 문제를 작성하세요.
- 데이터의 오류나 결측치를 확인하지 않고 다음 프로세스를 진행하여 지속적인 오류를 발생시킬 수 있다.

### 한계와 추가 확인 사항
아직 알 수 없는 품질 문제를 작성하세요.
- 결측, 중복 등의 세부 데이터 패턴 오류 문제

## 2. 결측·중복·키 품질
- 주요 ID 결측: 없음
- 주요 ID 중복: 없음
- 전체 행 중복: 없음

![결측 중복 점검](images/step02_quality.png)

### 결과 관찰
결측치와 중복은 없음

### 나의 해석과 판단
어떤 문제를 먼저 처리해야 하는지 우선순위를 작성하세요.
order_items.order_id는 한 주문에 여러 상품이 포함될 수 있기 때문에 반복될 수 있기에, 중복이 나와도 지우면 안됨.

### 업무·분석적 의미
- 기준 키에 결측과 중복이 없어서 고객·주문·상품 단위 집계에서 같은 대상이 두 번 세어질 위험이 낮다. 다음 단계인 테이블 결합과 관계 검증도 안정적으로 진행할 수 있다.
- 만약 orders.order_id가 중복되었다면 주문 건수와 매출이 부풀려지고, 결합 시 행이 불어난다. 결측이 있었다면 결합에서 빠지는 행이 생겨 분석 대상이 조용히 줄어든다.
- 중복이 없다는 결과는 "정상 데이터"라는 뜻이 아니라 "기계적으로 겹치는 행이 없다"는 뜻이다. 같은 주문이 다른 ID로 이중 입력된 경우처럼 의미상의 중복은 이 점검으로 잡히지 않는다.

### 한계와 추가 확인 사항
각 데이터의 특성과 연관 관계를 이해하고 있어야 중복과 결측치에 대한 올바른 판단으로 후행 작업을 올바르게 진행할 수 있음

## 3. 숫자형·범주형·날짜 점검
- 숫자형 범위에서 주목한 값: order_items.quantity는 1~5(평균 약 3.05, 중앙값 3), unit_price는 5,000~200,000원(평균 약 108,562원, 중앙값 111,000원)  
- 범주형 빈도에서 주목한 값: order_status는 completed 184건(61.3%), cancelled 64건(21.3%), refunded 52건(17.3%). 취소·환불 합계가 116건(약 38.7%)
- 날짜 변환 실패 건수: 0
- 날짜 범위: 가장 빠른 날짜: 2025-09-15 00:00:00 가장 최근 날짜: 2026-09-14 00:00:00

![기본 분포와 날짜 확인](images/step03_distribution.png)

### 결과 관찰
- order_items 764행 모두 quantity, unit_price에 값이 있고(count 764), quantity는 1~5, unit_price는 5,000~200,000 범위 안에 있다. 
- unit_price의 평균(약 10.9만)과 중앙값(11.1만)이 비슷해 한쪽으로 크게 치우치지 않았고, 최소·최대값도 극단적으로 튀지 않는다.
- 주문 300건 중 취소와 환불이 약 39%를 차지한다. 주문 상태 값은 3종류뿐이며 표기 불일치나 결측은 없다.
- order_date는 전부 날짜로 변환되었고(실패 0건), 미래 날짜나 비정상적으로 오래된 날짜 없이 1년 범위 안에 있다.

### 나의 해석과 판단
이상해 보이는 값이 실제 오류인지 업무적으로 가능한 값인지 구분하기 위해 무엇을 더 확인해야 하는지 작성하세요.
- 취소·환불 비중(약 39%): 데이터가 원래 그런 것인지, 상태 코드의 정의가 다른 것인지 업무 기준을 확인한다. 이 비중이 크면 매출·주문 분석에서 어떤 상태를 포함할지에 따라 결과가 크게 달라진다.
- unit_price 5,000원과 200,000원: products.price와 비교해 실제 상품 가격 범위 안의 값인지, 주문 시점 가격과 현재 가격이 다른 것인지 확인한다.
- 날짜: 월별 주문 건수를 보고 특정 달에 데이터가 비어 있거나 몰려 있지 않은지 확인한다.

### 업무·분석적 의미
- 주문 상태는 orders에만 있고 order_items에는 없다. 그래서 상품·금액 기준 매출을 계산하려면 orders와 결합한 뒤 어떤 상태를 매출로 인정할지 먼저 정해야 한다. completed만 쓸지, 환불을 차감할지에 따라 매출이 달라진다.
- quantity × unit_price로 라인 금액을 만들 수 있으며, 주문 단위 집계는 order_id 기준으로 묶어서 계산한다.
- 분석 기간이 정확히 1년치라 월별 추이는 볼 수 있지만, 계절성은 한 주기만 관찰할 수 있어 전년 대비 비교는 어렵다.

### 한계와 추가 확인 사항
- unit_price와 products.price의 일치 여부, 취소·환불 주문의 상세 사유는 이번 점검에서 확인하지 못했다.
- customers.signup_date는 아직 문자열이므로 날짜 변환 후 가입일이 주문일보다 늦은 고객이 있는지 점검이 필요하다.

## 4. CSV 간 키 관계 검증
- 없는 `customer_id`: 0건
- 없는 `order_id`: 0건
- 없는 `product_id`: 0건

![PK FK 관계 검증](images/step04_relationship.png)

### 결과 관찰
- 세 가지 키 관계(orders.customer_id → customers, order_items.order_id → orders, order_items.product_id → products)에서 부모 테이블에 없는 값은 모두 0건이다.
- 고아 행이 없어서 고객 → 주문 → 상품 라인 → 상품으로 이어지는 연결이 끊기지 않는다.

### 나의 해석과 판단
키 관계 문제가 발견되었다면 바로 삭제하면 안 되는 이유를 작성하세요.
- 원인이 입력 오류인지 마스터 파일의 추출 시점 차이인지 알 수 없고, 삭제하면 실제 매출과 주문 이력이 사라지며, orders를 지우면 그 주문의 order_items까지 고아 행이 되어 정합성이 다시 깨지기 때문이다. 먼저 해당 행을 확인하고 원인을 파악한 뒤 보존, 플래그 표시, 분석 제외 중에서 선택하고 건수와 기준을 기록해야 한다.

### 업무·분석적 의미
- 키 관계가 온전하므로 orders–order_items–products–customers를 결합해 고객·상품·기간별 분석을 진행할 수 있다.
- 결합해도 매칭되지 않는 행이 없어서, 결합 과정에서 분석 대상이 조용히 빠질 위험은 낮다.
- 관계가 1:N이므로 결합 시 주문 단위 값이 상품 행마다 복제된다. 결합 전후 행 수를 비교하고, 주문 단위 값은 집계한 뒤에 합산해야 한다.

### 한계와 추가 확인 사항
- 이번 검증은 키 값이 존재하는지만 확인한 것이며, 연결된 값이 업무적으로 맞는지는 확인하지 못했다. 예를 들어 unit_price와 products.price의 일치 여부, 가입일 이전 주문 여부는 별도로 점검해야 한다.
- 반대 방향(주문 없는 고객, 판매 이력 없는 상품, 상품 라인 없는 주문)은 확인하지 않았다.


## 5. LLM 구조 설명 검증
- LLM에 제공한 Safe Context: 온라인 쇼핑몰 데이터는 customers, products, orders, order_items의 4개 테이블로 구성되어 있다. customers는 150행이며 customer_id가 고유하고, age·city·signup_date를 포함한다. 각 테이블의 주요 ID는 결측이나 중복이 없으며, 테이블 간 연결에 사용하는 customer_id·order_id·product_id도 모두 참조 대상 테이블에 존재한다.
- LLM이 제안한 추가 점검: 데이터 타입 및 날짜 형식, 비주요 컬럼의 결측 패턴, 연령·수량·가격의 허용 범위, city·category·order_status의 표기 통일성, 가입일과 주문일의 시간 순서, 주문과 주문항목 간 완전성, 주문 상태별 취소·환불 처리 기준, 상품 기준가와 실제 판매단가의 차이, 주문 금액 계산의 정합성, 업무상 중복 주문, 이상치, 데이터 기간의 연속성,, 고객 프로필 분포, 그리고 매출/주문/고객 수의 분석 기준 정의를 제안하였다.
- 실제 데이터에서 확인한 항목: customers의 customer_id, products의 product_id, orders의 order_id, order_items의 order_item_id는 모두 고유했다. 주요 ID 컬럼의 결측값과 중복값은 없었다. 또한 orders의 customer_id, order_items의 order_id 및 product_id는 모두 연결 대상 테이블에 존재하여 기본적인 참조 무결성이 확보되었다
- 채택/수정/보류한 내용: 우선 채택할 항목은 주문 상태별 처리 기준, 주문-주문항목 완전성, 날짜 논리성, 수량,단가 이상치, 범주형 값 표준화이다. 가격 정합성과 주문 금액 계산 검증은 할인·배송비·세금·쿠폰 관련 컬럼의 존재 여부를 확인한 뒤 수행하도록 수정한다. 고객 프로필 분포와 업무상 중복 주문 탐지는 분석 목적과 주문 데이터의 시간 단위가 정해진 뒤 보류한다.

![LLM 구조 검토](images/step05_llm.png)

### 나의 해석과 판단
LLM 제안 중 가장 유용했던 것과 가장 조심해야 할 것을 작성하세요.

### 한계와 추가 확인 사항

## 6. Chapter 03 최종 판단
### 데이터의 첫인상 3가지
1.네 개의 테이블이 고객, 상품, 주문, 주문항목의 구조로 잘 분리되어 있어 고객·상품·매출 분석을 수행하기에 적절한 관계형 데이터 구조를 갖추고 있다.
2.주요 ID의 결측과 중복이 없고 테이블 간 연결 대상도 모두 존재하므로, 기본적인 데이터 무결성은 비교적 양호한 것으로 판단된다.
3.주문 상태·가격·날짜·수량에 대한 업무 규칙을 확인해야 신뢰할 수 있는 분석이 가능하다.

### 다음 Chapter 전에 반드시 확인/처리해야 할 항목
1.완료·취소·환불·결제 대기 등 주문 상태별 분석 포함 기준을 정의한다.
2.가입일과 주문일의 시간 순서, 날짜 형식, 수량·단가·연령의 비정상값을 점검한다.
3.city, category, order_status의 오타·공백·표기 불일치를 정리하고, 주문과 주문항목 간 누락 여부를 확인한다.

### 현재 데이터만으로 단정할 수 없는 것
매출이 실제로 증가하거나 감소했는지와 그 원인
특정 고객군이나 상품 카테고리가 성과가 좋거나 나쁜 이유
할인·취소·환불을 반영한 실제 순매출 및 수익성
고객의 장기 재구매 성향

## 최종 제출 체크
- [O] Notebook을 처음부터 끝까지 실행했습니다.
- [O] 오류 셀이 남아 있지 않습니다.
- [O] 핵심 Evidence를 첨부했습니다.
- [O] 관찰과 해석을 구분했습니다.
- [O] 개인정보/Secret이 없습니다.
- [O] `chapter03/chapter03.ipynb`가 GitHub에서 정상 표시됩니다.
- [O] 최종 Notebook 파일 URL을 제출합니다.

# 3장. 데이터의 첫인상 읽기

이 노트북은 강의안 `book/chapters/ch03_data_first_impression.md`를 따라가며 직접 실행해 보는 실습용 자료입니다.

이번 장의 목표는 멋진 분석 결과를 바로 만드는 것이 아니라, 분석 전에 데이터가 어떤 모양인지 차분히 확인하는 습관을 만드는 것입니다. 코드를 한 셀씩 실행하면서 출력 결과를 보고, 바로 아래 설명과 질문에 답해 보세요.

## 0. 이번 장에서 확인할 것

데이터를 처음 열었을 때는 다음 질문에 답할 수 있어야 합니다.

- 데이터 파일은 몇 개인가?
- 각 파일은 어떤 역할을 하는가?
- 각 파일은 몇 행, 몇 열로 구성되어 있는가?
- 어떤 컬럼이 있고, 각 컬럼은 어떤 의미를 가지는가?
- 숫자, 문자, 날짜 컬럼은 무엇인가?
- 비어 있는 값이나 중복된 값은 없는가?
- 여러 파일을 연결할 수 있는 기준 컬럼은 무엇인가?
- LLM이 설명한 데이터 구조가 실제 데이터와 일치하는가?

![CSV 파일을 pandas DataFrame으로 불러오는 흐름](../book/assets/images/ch03/ch03_csv_to_dataframe_flow.svg)

CSV 파일은 텍스트 파일이지만, pandas로 불러오면 행과 열을 가진 `DataFrame`으로 다룰 수 있습니다.

## 1. 실습 준비

먼저 필요한 패키지를 불러오고, 프로젝트 폴더와 데이터 폴더를 찾습니다. 노트북을 `notebooks` 폴더에서 실행해도 되고, 프로젝트 루트에서 실행해도 되도록 `find_project_root()` 함수를 사용합니다.

In [5]:
from pathlib import Path

import pandas as pd

pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 120)


def find_project_root(start: Path) -> Path:
    """현재 위치에서 위로 올라가며 data/raw 폴더가 있는 프로젝트 루트를 찾습니다."""
    start = start.resolve()
    for candidate in [start, *start.parents]:
        if (candidate / "data" / "raw").exists():
            return candidate
    raise FileNotFoundError("프로젝트 루트를 찾지 못했습니다. 노트북을 저장소 안에서 실행해 주세요.")


PROJECT_ROOT = find_project_root(Path.cwd())
DATA_DIR = PROJECT_ROOT / "data" / "raw"

print("프로젝트 루트:", PROJECT_ROOT)
print("데이터 폴더:", DATA_DIR)

프로젝트 루트: C:\dev\llm-data-analysis-study
데이터 폴더: C:\dev\llm-data-analysis-study\data\raw

## 2. 데이터 파일이 있는지 확인하기

파일 경로 오류는 초보자가 가장 자주 만나는 오류입니다. 데이터를 불러오기 전에 필요한 CSV 파일이 실제로 있는지 먼저 확인합니다.

In [6]:
expected_files = [
    "customers.csv",
    "products.csv",
    "orders.csv",
    "order_items.csv",
]

file_check = pd.DataFrame({
    "file": expected_files,
    "path": [str(DATA_DIR / filename) for filename in expected_files],
    "exists": [(DATA_DIR / filename).exists() for filename in expected_files],
})

file_check

              file                                               path  exists
0    customers.csv  C:\dev\llm-data-analysis-study\data\raw\custom...    True
1     products.csv  C:\dev\llm-data-analysis-study\data\raw\produc...    True
2       orders.csv  C:\dev\llm-data-analysis-study\data\raw\orders...    True
3  order_items.csv  C:\dev\llm-data-analysis-study\data\raw\order_...    True

`exists`가 모두 `True`이면 다음 단계로 진행할 수 있습니다.

하나라도 `False`라면 데이터가 아직 생성되지 않았을 수 있습니다. 그 경우 터미널에서 아래 명령을 실행해 샘플 데이터를 생성합니다.

```bash
python scripts/generate_sample_data.py
```

## 3. CSV 파일을 DataFrame으로 불러오기

이제 4개의 CSV 파일을 pandas `DataFrame`으로 불러옵니다. 각 변수 이름은 파일 이름과 비슷하게 맞춰 두면 이후 코드를 읽기 쉽습니다.

In [7]:
customers = pd.read_csv(DATA_DIR / "customers.csv")
products = pd.read_csv(DATA_DIR / "products.csv")
orders = pd.read_csv(DATA_DIR / "orders.csv")
order_items = pd.read_csv(DATA_DIR / "order_items.csv")

print("customers:", type(customers))
print("products:", type(products))
print("orders:", type(orders))
print("order_items:", type(order_items))

customers: <class 'pandas.DataFrame'>
products: <class 'pandas.DataFrame'>
orders: <class 'pandas.DataFrame'>
order_items: <class 'pandas.DataFrame'>

분석할 데이터셋이 여러 개일 때는 딕셔너리로 묶어 두면 반복 점검을 하기 편합니다.

In [8]:
datasets = {
    "customers": customers,
    "products": products,
    "orders": orders,
    "order_items": order_items,
}

list(datasets.keys())

['customers', 'products', 'orders', 'order_items']

## 4. 각 파일의 역할 이해하기

이번 과정에서 사용하는 데이터는 가상의 온라인 쇼핑몰 운영 데이터입니다.

| 파일 | 역할 | 먼저 확인할 것 |
| --- | --- | --- |
| `customers.csv` | 고객 정보 | 고객 수, 연령, 성별, 지역, 가입일 |
| `products.csv` | 상품 정보 | 상품 수, 카테고리, 가격 |
| `orders.csv` | 주문 정보 | 주문 수, 주문일, 결제수단, 주문상태 |
| `order_items.csv` | 주문 상세 정보 | 주문별 상품, 수량, 단가 |

처음에는 파일을 합치지 말고, 각 파일을 따로 살펴보는 것이 좋습니다.

![pandas DataFrame 구조 예시](../book/assets/images/ch03/ch03_dataframe_structure.svg)

DataFrame은 행(row)과 열(column)로 구성됩니다. `shape`, `head()`, `columns`, `info()` 같은 기본 도구를 사용해 구조를 확인합니다.

## 5. 데이터 크기 확인하기

`shape`는 데이터의 행과 열 개수를 알려 줍니다.

- 앞 숫자: 행 개수
- 뒤 숫자: 열 개수

예를 들어 `(150, 6)`은 150행 6열이라는 뜻입니다.

In [9]:
print("customers:", customers.shape)
print("products:", products.shape)
print("orders:", orders.shape)
print("order_items:", order_items.shape)

customers: (150, 6)
products: (100, 4)
orders: (300, 5)
order_items: (764, 5)

In [10]:
shape_summary = pd.DataFrame([
    {
        "dataset": name,
        "rows": df.shape[0],
        "columns": df.shape[1],
    }
    for name, df in datasets.items()
])

shape_summary

       dataset  rows  columns
0    customers   150        6
1     products   100        4
2       orders   300        5
3  order_items   764        5

### 생각해 보기

- 가장 행이 많은 데이터셋은 무엇인가요? 
order_items가 764행으로 가장 많습니다
- `order_items`가 `orders`보다 행이 많다면, 그 이유는 무엇일까요? 
두 테이블은 1:N 관계이기 때문입니다. orders는 주문 1건이 1행이고, order_items는 주문 안에 담긴 상품 1개가 1행입니다. 그래서 한 주문에서 상품을 여러 개 사면 orders에는 1행만 생기지만 order_items에는 상품 수만큼 행이 생깁니다.
- 분석 보고서에 데이터 규모를 설명한다면 어떤 문장으로 쓸 수 있을까요?
본 분석에 사용한 데이터는 고객(150행 × 6열), 상품(100행 × 4열), 주문(300행 × 5열), 주문 상세(764행 × 5열)의 4개 테이블로 고객 150명, 상품 100종, 주문 300건 및 주문 상세 764건으로 구성된다. 주문 상세 테이블은 주문 1건에 여러 상품이 포함되는 구조로, 주문당 평균 약 2.5개 품목이 포함되어 있다.

## 6. 데이터 앞부분과 마지막 부분 보기

`head()`는 앞부분 5행을 보여 줍니다. 컬럼명이 예상과 맞는지, 값의 형태가 자연스러운지 빠르게 확인할 때 사용합니다.

In [11]:
customers.head()

   customer_id name gender  age city signup_date
0            1  김수민      F   19   광주  2024-08-26
1            2  김정호      F   32   대구  2026-01-09
2            3  이경수      F   61   성남  2024-08-19
3            4  조영호      F   55   울산  2026-06-20
4            5  이예원      F   19   부산  2024-11-20

In [12]:
products.head()

   product_id product_name category   price
0           1  전자기기 상품 001     전자기기  160000
1           2    도서 상품 002       도서   34000
2           3  전자기기 상품 003     전자기기  152000
3           4  생활용품 상품 004     생활용품   70000
4           5    식품 상품 005       식품  186000

In [13]:
orders.head()

   order_id  customer_id  order_date payment_method order_status
0         1          123  2026-07-14           card    completed
1         2           77  2025-09-29      naver_pay    cancelled
2         3          138  2026-01-26  bank_transfer    cancelled
3         4           57  2026-04-08      kakao_pay    cancelled
4         5          125  2026-02-27           card    cancelled

In [14]:
order_items.head()

   order_item_id  order_id  product_id  quantity  unit_price
0              1         1         100         3      102000
1              2         1          87         5       25000
2              3         1           7         3      142000
3              4         1           9         3      193000
4              5         2          72         4      189000

앞부분만 보고 전체 데이터가 정상이라고 판단하기는 어렵습니다. `tail()`로 마지막 부분도 확인해 봅니다.

In [15]:
customers.tail()

     customer_id name gender  age city signup_date
145          146  김숙자      M   61   성남  2026-03-01
146          147  이정남      M   19   부산  2025-04-20
147          148  오도현      M   29   고양  2026-08-22
148          149  김정자      M   20   부산  2024-12-26
149          150  조미영      M   40   대전  2026-02-10

### 생각해 보기

`head()`와 `tail()`을 보면서 아래를 확인해 보세요.

- 날짜처럼 보이는 컬럼이 있나요? 
customers : signup_date (가입일)
orders	 : order_date (주문일)
- 숫자처럼 보이는 컬럼이 있나요?
customers : age	(나이)
products : price (정가)
order_items: quantity, unit_price (수량, 판매 단가)
- ID처럼 보이는 컬럼이 있나요? 
customers: customer_id	
products : product_id	
orders : order_id, customer_id 
order_items : order_item_id, order_id, product_id	
- 사람이 직접 읽을 수 있는 이름이나 범주 값이 있나요?
이름(텍스트): name(고객명), product_name(상품명)
gender: F, M
city: 광주, 대구, 부산 등
category: 전자기기, 도서, 생활용품, 식품
payment_method: card, naver_pay, kakao_pay, bank_transfer
order_status: completed, cancelled

## 7. 컬럼명 확인하기

컬럼명은 코드 작성에서 매우 중요합니다. 실제 컬럼명이 `customer_id`인데 LLM이나 사람이 `cust_id`라고 쓰면 코드는 실행되지 않습니다.

In [16]:
for name, df in datasets.items():
    print(f"[{name}]")
    print(list(df.columns))
    print()

[customers]
['customer_id', 'name', 'gender', 'age', 'city', 'signup_date']

[products]
['product_id', 'product_name', 'category', 'price']

[orders]
['order_id', 'customer_id', 'order_date', 'payment_method', 'order_status']

[order_items]
['order_item_id', 'order_id', 'product_id', 'quantity', 'unit_price']

In [17]:
column_summary = pd.DataFrame([
    {
        "dataset": name,
        "column_count": len(df.columns),
        "column_names": ", ".join(df.columns),
    }
    for name, df in datasets.items()
])

column_summary

       dataset  column_count                                       column_names
0    customers             6  customer_id, name, gender, age, city, signup_date
1     products             4          product_id, product_name, category, price
2       orders             5  order_id, customer_id, order_date, payment_met...
3  order_items             5  order_item_id, order_id, product_id, quantity,...

### 생각해 보기

- 고객을 구분하는 컬럼은 무엇인가요?
customer_id
customers 테이블의 기본키이고, orders에도 들어 있어 "누가 주문했는지"를 알려 줍니다.
- 주문을 구분하는 컬럼은 무엇인가요?
order_id
orders의 기본키입니다. order_items에도 있어서 각 품목이 어느 주문에 속하는지 알려 줍니다.
참고로 order_items에서 품목 한 줄을 구분하는 컬럼은 order_item_id입니다.
- 상품을 구분하는 컬럼은 무엇인가요?
product_id
products의 기본키이고, order_items에서 "어떤 상품을 샀는지"를 가리킵니다.
- 여러 파일을 연결할 때 사용할 수 있을 것 같은 컬럼은 무엇인가요?
공통 컬럼/연결되는 테이블/관계
customer_id/customers ↔ orders/고객 1명 : 주문 여러 건
order_id/orders ↔ order_items/주문 1건 : 품목 여러 개
product_id/products ↔ order_items/상품 1개 : 품목 여러 개

## 8. 데이터 타입 확인하기

`info()`는 컬럼별 데이터 타입과 비어 있지 않은 값의 개수를 보여 줍니다.

특히 날짜처럼 보이지만 `object`로 저장된 컬럼을 주의해서 봅니다. pandas에서 `object`는 보통 문자열 또는 여러 타입이 섞인 컬럼일 때 나타납니다.

In [18]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  150 non-null    int64
 1   name         150 non-null    str
 2   gender       150 non-null    str
 3   age          150 non-null    int64
 4   city         150 non-null    str
 5   signup_date  150 non-null    str
dtypes: int64(2), str(4)
memory usage: 11.0 KB

In [19]:
for name, df in datasets.items():
    print(f"\n===== {name} =====")
    df.info()

===== customers =====
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  150 non-null    int64
 1   name         150 non-null    str
 2   gender       150 non-null    str
 3   age          150 non-null    int64
 4   city         150 non-null    str
 5   signup_date  150 non-null    str
dtypes: int64(2), str(4)
memory usage: 11.0 KB

===== products =====
<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    100 non-null    int64
 1   product_name  100 non-null    str
 2   category      100 non-null    str
 3   price         100 non-null    int64
dtypes: int64(2), str(2)
memory usage: 6.0 KB

===== orders =====
<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        300 non-null    int64
 1   customer_id     300 non-null    int64
 2   order_date      300 non-null    str
 3   payment_method  300 non-null    str
 4   order_status    300 non-null    str
dtypes: int64(2), str(3)
memory usage: 19.9 KB

===== order_items =====
<class 'pandas.DataFrame'>
RangeIndex: 764 entries, 0 to 763
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  764 non-null    int64
 1   order_id       764 non-null    int64
 2   product_id     764 non-null    int64
 3   quantity       764 non-null    int64
 4   unit_price     764 non-null    int64
dtypes: int64(5)
memory usage: 30.0 KB

In [20]:
dtype_summary = pd.concat(
    [df.dtypes.rename(name) for name, df in datasets.items()],
    axis=1,
).fillna("")

dtype_summary

               customers products orders order_items
customer_id        int64           int64
name                 str
gender               str
age                int64
city                 str
signup_date          str
product_id                  int64              int64
product_name                  str
category                      str
price                       int64
order_id                           int64       int64
order_date                           str
payment_method                       str
order_status                         str
order_item_id                                  int64
quantity                                       int64
unit_price                                     int64

### 생각해 보기

- 숫자형 컬럼은 어떤 것들이 있나요?
테이블/컬럼
customers / customer_id, age
products / product_id, price
orders / order_id, customer_id
order_items /order_item_id, order_id, product_id, quantity, unit_price
- 문자형 컬럼은 어떤 것들이 있나요?
테이블 / 컬럼
customers / name, gender, city, signup_date
products / product_name, category
orders / order_date, payment_method, order_status
- 날짜처럼 보이지만 아직 문자열일 가능성이 있는 컬럼은 무엇인가요?
customers.signup_date
orders.order_date

![데이터 구조 점검 흐름도](../book/assets/images/ch03/ch03_data_check_flow.svg)

데이터 구조 점검은 파일 확인, 로드, 크기 확인, 컬럼 확인, 타입 확인, 결측치 확인, 중복 확인, 키 관계 확인 순서로 진행하면 좋습니다.

## 9. 결측치 확인하기

결측치는 값이 비어 있는 상태입니다. 결측치가 있으면 평균, 비율, 그룹별 집계 결과가 달라질 수 있습니다.

`isna().sum()`은 컬럼별 결측치 개수를 계산합니다.

In [21]:
customers.isna().sum()

customer_id    0
name           0
gender         0
age            0
city           0
signup_date    0
dtype: int64

In [22]:
missing_summary = pd.concat(
    [df.isna().sum().rename(name) for name, df in datasets.items()],
    axis=1,
).fillna("").astype(str)

missing_summary

               customers products orders order_items
customer_id          0.0             0.0
name                 0.0
gender               0.0
age                  0.0
city                 0.0
signup_date          0.0
product_id                    0.0                0.0
product_name                  0.0
category                      0.0
price                         0.0
order_id                             0.0         0.0
order_date                           0.0
payment_method                       0.0
order_status                         0.0
order_item_id                                    0.0
quantity                                         0.0
unit_price                                       0.0

In [23]:
missing_rate_summary = pd.concat(
    [(df.isna().mean() * 100).round(2).rename(name) for name, df in datasets.items()],
    axis=1,
).fillna("")

missing_rate_summary

               customers products orders order_items
customer_id          0.0             0.0
name                 0.0
gender               0.0
age                  0.0
city                 0.0
signup_date          0.0
product_id                    0.0                0.0
product_name                  0.0
category                      0.0
price                         0.0
order_id                             0.0         0.0
order_date                           0.0
payment_method                       0.0
order_status                         0.0
order_item_id                                    0.0
quantity                                         0.0
unit_price                                       0.0

### 결측치 해석 팁

결측치가 있다고 해서 무조건 삭제하는 것은 아닙니다.

| 처리 방법 | 설명 |
| --- | --- |
| 행 제외 | 결측치가 있는 행을 분석에서 제외합니다. |
| 대표값 대체 | 평균, 중앙값, 최빈값 등으로 채웁니다. |
| 별도 범주 처리 | `Unknown` 같은 범주로 표시합니다. |
| 컬럼 제외 | 분석 목적에 맞지 않는 컬럼은 사용하지 않습니다. |
| 원인 확인 | 수집 과정에서 문제가 있었는지 확인합니다. |

## 10. 중복 데이터 확인하기

중복은 같은 행이나 같은 ID가 반복되는 상태입니다.

단, 모든 중복이 오류는 아닙니다. 예를 들어 `order_items`에서는 한 주문에 여러 상품이 들어갈 수 있으므로 같은 `order_id`가 여러 번 나올 수 있습니다.

In [24]:
duplicate_rows = pd.DataFrame([
    {
        "dataset": name,
        "duplicated_rows": df.duplicated().sum(),
    }
    for name, df in datasets.items()
])

duplicate_rows

       dataset  duplicated_rows
0    customers                0
1     products                0
2       orders                0
3  order_items                0

In [25]:
id_duplicate_checks = pd.DataFrame([
    {
        "check": "customers.customer_id",
        "duplicated_count": customers["customer_id"].duplicated().sum(),
        "interpretation": "0이어야 고객 ID가 유일합니다.",
    },
    {
        "check": "products.product_id",
        "duplicated_count": products["product_id"].duplicated().sum(),
        "interpretation": "0이어야 상품 ID가 유일합니다.",
    },
    {
        "check": "orders.order_id",
        "duplicated_count": orders["order_id"].duplicated().sum(),
        "interpretation": "0이어야 주문 ID가 유일합니다.",
    },
    {
        "check": "order_items.order_id",
        "duplicated_count": order_items["order_id"].duplicated().sum(),
        "interpretation": "한 주문에 여러 상품이 있으면 0보다 클 수 있습니다.",
    },
])

id_duplicate_checks

                   check  duplicated_count                  interpretation
0  customers.customer_id                 0              0이어야 고객 ID가 유일합니다.
1    products.product_id                 0              0이어야 상품 ID가 유일합니다.
2        orders.order_id                 0              0이어야 주문 ID가 유일합니다.
3   order_items.order_id               464  한 주문에 여러 상품이 있으면 0보다 클 수 있습니다.

### 생각해 보기

- `customers.customer_id` 중복과 `order_items.order_id` 중복은 왜 의미가 다를까요?
두 컬럼이 테이블에서 하는 역할이 다르기 때문입니다.
- 중복 개수만 보고 삭제하면 위험한 이유는 무엇일까요?
정상 데이터가 사라집니다.
"중복"의 기준은 비즈니스 의미가 정합니다. 같은 상품을 같은 날 두 번 산 것은 실제 두 건의 구매일 수 있습니다. 어떤 컬럼 조합이 같아야 진짜 중복인지 먼저 정의해야 합니다.
어느 행을 남길지가 결과를 바꿉니다. 같은 ID에 값이 다른 행이 있으면, 무엇을 남기느냐에 따라 분석 결과가 달라집니다.
원인을 놓칩니다. 중복은 데이터 수집이나 병합 과정에 문제가 있다는 신호일 수 있습니다. 지우기만 하면 같은 문제가 계속 생깁니다.

## 11. 숫자형 컬럼 기본 통계 확인하기

`describe()`는 숫자형 컬럼의 개수, 평균, 표준편차, 최솟값, 사분위수, 최댓값을 보여 줍니다.

최솟값이나 최댓값이 지나치게 이상하면 데이터 오류나 이상치 가능성을 의심할 수 있습니다.

In [26]:
customers.describe()

       customer_id         age
count   150.000000  150.000000
mean     75.500000   42.086667
std      43.445368   15.613166
min       1.000000   19.000000
25%      38.250000   29.000000
50%      75.500000   40.000000
75%     112.750000   57.000000
max     150.000000   69.000000

In [27]:
products[["price"]].describe()

               price
count     100.000000
mean   110040.000000
std     56433.910574
min      5000.000000
25%     65750.000000
50%    112000.000000
75%    161000.000000
max    200000.000000

In [28]:
order_items[["quantity", "unit_price"]].describe()

         quantity     unit_price
count  764.000000     764.000000
mean     3.053665  108561.518325
std      1.410873   56996.770604
min      1.000000    5000.000000
25%      2.000000   62000.000000
50%      3.000000  111000.000000
75%      4.000000  161250.000000
max      5.000000  200000.000000

숫자가 문자열로 저장된 경우도 있습니다. 예를 들어 `"10,000"`처럼 쉼표가 포함된 문자열은 바로 계산하기 어렵습니다.

In [29]:
price_text = pd.Series(["10,000", "25,500", "3000", "확인필요"])
price_number = pd.to_numeric(
    price_text.str.replace(",", "", regex=False),
    errors="coerce",
)

pd.DataFrame({
    "original": price_text,
    "converted": price_number,
})

  original  converted
0   10,000    10000.0
1   25,500    25500.0
2     3000     3000.0
3     확인필요        NaN

`errors="coerce"`는 숫자로 바꿀 수 없는 값을 `NaN`으로 처리합니다. 변환 후에는 새로 생긴 결측치가 있는지도 확인해야 합니다.

## 12. 범주형 컬럼 고유값 확인하기

문자형 또는 범주형 컬럼은 고유값 개수와 빈도를 확인합니다. 예를 들어 지역, 성별, 카테고리, 주문 상태 같은 컬럼은 `value_counts()`로 분포를 볼 수 있습니다.

In [30]:
customers["city"].value_counts().head(10)

city
성남    21
광주    17
부산    16
대구    15
서울    15
울산    14
인천    14
대전    14
수원    13
고양    11
Name: count, dtype: int64

In [31]:
products["category"].value_counts()

category
스포츠     19
전자기기    17
생활용품    16
뷰티      16
도서      14
패션      11
식품       7
Name: count, dtype: int64

In [32]:
orders["order_status"].value_counts()

order_status
completed    184
cancelled     64
refunded      52
Name: count, dtype: int64

In [33]:
categorical_summary = pd.DataFrame([
    {"dataset": "customers", "column": "city", "unique_count": customers["city"].nunique()},
    {"dataset": "customers", "column": "gender", "unique_count": customers["gender"].nunique()},
    {"dataset": "products", "column": "category", "unique_count": products["category"].nunique()},
    {"dataset": "orders", "column": "payment_method", "unique_count": orders["payment_method"].nunique()},
    {"dataset": "orders", "column": "order_status", "unique_count": orders["order_status"].nunique()},
])

categorical_summary

     dataset          column  unique_count
0  customers            city            10
1  customers          gender             2
2   products        category             7
3     orders  payment_method             4
4     orders    order_status             3

### 생각해 보기

- 특정 값에 데이터가 지나치게 몰려 있나요?
city : 성남 14% ~ 고양 7.3%, 10개 도시, 비교적 고르게 분포
category : 스포츠 19% ~ 식품 7%, 7개 범주	대체로 고르지만 식품(7개)이 적음
order_status : completed 61.3%, cancelled 21.3%, refunded 17.3%, completed에 몰려 있지만, 취소·환불이 38.7%로 꽤 많음
- 오타나 표기 차이처럼 보이는 값이 있나요?
출력된 값 중에는 없습니다.
- 나중에 그룹별 분석 기준으로 쓰기 좋은 컬럼은 무엇인가요?
category : 카테고리별 매출, 판매 수량
city : 지역별 고객 수, 매출
gender : 성별 구매 금액 비교
payment_method : 결제 수단별 주문 수, 취소율
order_status : 그룹 기준보다는 필터(completed만 남기기)나 취소·환불률 계산에 사용

## 13. 날짜 컬럼 확인하기

날짜 컬럼은 월별, 요일별, 기간별 분석에 자주 사용됩니다.

하지만 CSV에서 읽어온 날짜는 처음에는 문자열(`object`)일 수 있습니다. `pd.to_datetime()`으로 날짜 타입으로 바꿔야 날짜 계산을 안전하게 할 수 있습니다.

In [34]:
orders["order_date"].head()

0    2026-07-14
1    2025-09-29
2    2026-01-26
3    2026-04-08
4    2026-02-27
Name: order_date, dtype: str

In [35]:
print("변환 전 타입:", orders["order_date"].dtype)

orders["order_date"] = pd.to_datetime(orders["order_date"], errors="coerce")

print("변환 후 타입:", orders["order_date"].dtype)
print("날짜 변환 실패 건수:", orders["order_date"].isna().sum())
print("가장 빠른 주문일:", orders["order_date"].min())
print("가장 최근 주문일:", orders["order_date"].max())

변환 전 타입: str
변환 후 타입: datetime64[us]
날짜 변환 실패 건수: 0
가장 빠른 주문일: 2025-09-15 00:00:00
가장 최근 주문일: 2026-09-14 00:00:00

In [36]:
orders.assign(
    order_year=orders["order_date"].dt.year,
    order_month=orders["order_date"].dt.month,
    order_day_name=orders["order_date"].dt.day_name(),
).head()

   order_id  customer_id order_date payment_method order_status  order_year  order_month order_day_name
0         1          123 2026-07-14           card    completed        2026            7        Tuesday
1         2           77 2025-09-29      naver_pay    cancelled        2025            9         Monday
2         3          138 2026-01-26  bank_transfer    cancelled        2026            1         Monday
3         4           57 2026-04-08      kakao_pay    cancelled        2026            4      Wednesday
4         5          125 2026-02-27           card    cancelled        2026            2         Friday

### 생각해 보기

- 데이터는 어느 기간을 포함하고 있나요?
2025-09-15 ~ 2026-09-14, 1년(365일)입니다.
- 월별 매출 분석을 하기에 충분한 기간인가요?
12개월이 모두 포함되어 있어 월별 흐름을 한 바퀴 볼 수 있습니다.
- 날짜 변환 실패 건수가 0보다 크다면 무엇을 확인해야 할까요?
원본 값을 봐야 원인을 알 수 있습니다.

## 14. 여러 파일의 관계 확인하기

온라인 쇼핑몰 데이터는 고객, 상품, 주문, 주문 상세 데이터가 서로 연결되어야 분석할 수 있습니다.

| 연결 관계 | 의미 |
| --- | --- |
| `customers.customer_id` ↔ `orders.customer_id` | 어떤 고객이 주문했는지 연결합니다. |
| `orders.order_id` ↔ `order_items.order_id` | 주문과 주문 상세를 연결합니다. |
| `products.product_id` ↔ `order_items.product_id` | 주문 상세와 상품 정보를 연결합니다. |

![4개 CSV 파일 간 키 관계도](../book/assets/images/ch03/ch03_csv_key_relationships.svg)

In [37]:
invalid_customers = orders[~orders["customer_id"].isin(customers["customer_id"])]
invalid_orders = order_items[~order_items["order_id"].isin(orders["order_id"])]
invalid_products = order_items[~order_items["product_id"].isin(products["product_id"])]

relationship_check = pd.DataFrame([
    {
        "relationship": "orders.customer_id -> customers.customer_id",
        "invalid_rows": len(invalid_customers),
    },
    {
        "relationship": "order_items.order_id -> orders.order_id",
        "invalid_rows": len(invalid_orders),
    },
    {
        "relationship": "order_items.product_id -> products.product_id",
        "invalid_rows": len(invalid_products),
    },
])

relationship_check

                                    relationship  invalid_rows
0    orders.customer_id -> customers.customer_id             0
1        order_items.order_id -> orders.order_id             0
2  order_items.product_id -> products.product_id             0

`invalid_rows`가 모두 0이면 샘플 데이터에서는 기본적인 연결 관계가 유지되고 있다고 볼 수 있습니다. 0보다 큰 값이 있다면 어느 파일에서 기준 ID가 빠져 있는지 먼저 확인해야 합니다.

## 15. 간단한 병합으로 관계 확인하기

키 관계가 맞는지 확인한 뒤에는 데이터를 병합해 볼 수 있습니다. 아래 코드는 주문 상세(`order_items`)에 상품 정보(`products`)를 붙이고, 각 행의 금액을 계산합니다.

In [38]:
order_items_with_products = order_items.merge(
    products,
    on="product_id",
    how="left",
)

order_items_with_products["line_amount"] = (
    order_items_with_products["quantity"] * order_items_with_products["unit_price"]
)

order_items_with_products.head()

   order_item_id  order_id  product_id  quantity  unit_price product_name category   price  line_amount
0              1         1         100         3      102000    도서 상품 100       도서  102000       306000
1              2         1          87         5       25000    도서 상품 087       도서   25000       125000
2              3         1           7         3      142000    도서 상품 007       도서  142000       426000
3              4         1           9         3      193000   스포츠 상품 009      스포츠  193000       579000
4              5         2          72         4      189000    뷰티 상품 072       뷰티  189000       756000

In [39]:
category_sales = (
    order_items_with_products
    .groupby("category", as_index=False)["line_amount"]
    .sum()
    .sort_values("line_amount", ascending=False)
)

category_sales

  category  line_amount
3      스포츠     50174000
1       뷰티     47551000
5     전자기기     41003000
2     생활용품     34839000
4       식품     33597000
0       도서     24645000
6       패션     23801000

이 결과는 본격적인 EDA가 아니라, 데이터 관계가 실제로 연결되는지 확인하는 작은 점검입니다. 분석 결론을 내리기 전에 결측치, 주문 상태, 취소 주문 처리 기준 등을 더 확인해야 합니다.

## 16. 반복 점검을 함수로 정리하기

여러 데이터셋에 같은 점검을 반복할 때는 함수로 정리하면 편합니다.

In [40]:
def check_data_overview(name: str, df: pd.DataFrame) -> None:
    print(f"===== {name} =====")
    print("shape:", df.shape)
    print("\ncolumns:")
    print(list(df.columns))
    print("\ndtypes:")
    print(df.dtypes)
    print("\nmissing values:")
    print(df.isna().sum())
    print("\nduplicated rows:", df.duplicated().sum())


check_data_overview("customers", customers)

===== customers =====
shape: (150, 6)

columns:
['customer_id', 'name', 'gender', 'age', 'city', 'signup_date']

dtypes:
customer_id    int64
name             str
gender           str
age            int64
city             str
signup_date      str
dtype: object

missing values:
customer_id    0
name           0
gender         0
age            0
city           0
signup_date    0
dtype: int64

duplicated rows: 0

In [41]:
for name, df in datasets.items():
    check_data_overview(name, df)
    print()

===== customers =====
shape: (150, 6)

columns:
['customer_id', 'name', 'gender', 'age', 'city', 'signup_date']

dtypes:
customer_id    int64
name             str
gender           str
age            int64
city             str
signup_date      str
dtype: object

missing values:
customer_id    0
name           0
gender         0
age            0
city           0
signup_date    0
dtype: int64

duplicated rows: 0

===== products =====
shape: (100, 4)

columns:
['product_id', 'product_name', 'category', 'price']

dtypes:
product_id      int64
product_name      str
category          str
price           int64
dtype: object

missing values:
product_id      0
product_name    0
category        0
price           0
dtype: int64

duplicated rows: 0

===== orders =====
shape: (300, 5)

columns:
['order_id', 'customer_id', 'order_date', 'payment_method', 'order_status']

dtypes:
order_id                   int64
customer_id                int64
order_date        datetime64[us]
payment_method               str
order_status                 str
dtype: object

missing values:
order_id          0
customer_id       0
order_date        0
payment_method    0
order_status      0
dtype: int64

duplicated rows: 0

===== order_items =====
shape: (764, 5)

columns:
['order_item_id', 'order_id', 'product_id', 'quantity', 'unit_price']

dtypes:
order_item_id    int64
order_id         int64
product_id       int64
quantity         int64
unit_price       int64
dtype: object

missing values:
order_item_id    0
order_id         0
product_id       0
quantity         0
unit_price       0
dtype: int64

duplicated rows: 0

![Jupyter Notebook 데이터 구조 점검 결과 화면 예시](../book/assets/images/ch03/ch03_jupyter_data_overview_result.svg)

## 17. LLM에게 데이터 구조를 설명시키는 법

LLM에게 원본 데이터를 그대로 붙여 넣는 것은 피하는 것이 좋습니다. 대신 아래처럼 구조 요약만 전달합니다.

- 파일명
- 컬럼명
- 행과 열 개수
- 데이터 타입
- 결측치 개수
- 중복 여부
- 파일 간 키 관계

In [42]:
llm_dataset_summary = shape_summary.merge(column_summary, on="dataset")
llm_dataset_summary

       dataset  rows  columns  column_count                                       column_names
0    customers   150        6             6  customer_id, name, gender, age, city, signup_date
1     products   100        4             4          product_id, product_name, category, price
2       orders   300        5             5  order_id, customer_id, order_date, payment_met...
3  order_items   764        5             5  order_item_id, order_id, product_id, quantity,...

In [43]:
for _, row in llm_dataset_summary.iterrows():
    print(f"- {row['dataset']}: {row['rows']}행 {row['columns']}열")
    print(f"  컬럼: {row['column_names']}")

- customers: 150행 6열
  컬럼: customer_id, name, gender, age, city, signup_date
- products: 100행 4열
  컬럼: product_id, product_name, category, price
- orders: 300행 5열
  컬럼: order_id, customer_id, order_date, payment_method, order_status
- order_items: 764행 5열
  컬럼: order_item_id, order_id, product_id, quantity, unit_price

### 데이터 구조 설명 요청 예시

아래 프롬프트는 LLM에게 붙여 넣을 수 있는 예시입니다. 실제 데이터 전체가 아니라 구조 정보만 포함합니다.

In [44]:
prompt = f"""
온라인 쇼핑몰 데이터 분석을 시작하기 전에 다음 CSV 파일들의 구조를 이해하려고 합니다.

데이터셋 요약:
{llm_dataset_summary[['dataset', 'rows', 'columns', 'column_names']].to_string(index=False)}

파일 간 관계:
- customers.customer_id -> orders.customer_id
- orders.order_id -> order_items.order_id
- products.product_id -> order_items.product_id

요청:
1. 각 파일이 어떤 역할을 하는지 설명해 주세요.
2. 분석 전에 확인해야 할 항목을 체크리스트로 정리해 주세요.
3. 실제 데이터 확인 없이 단정한 내용과 추가 확인이 필요한 내용을 구분해 주세요.
"""

print(prompt)

온라인 쇼핑몰 데이터 분석을 시작하기 전에 다음 CSV 파일들의 구조를 이해하려고 합니다.

데이터셋 요약:
    dataset  rows  columns                                                    column_names
  customers   150        6               customer_id, name, gender, age, city, signup_date
   products   100        4                       product_id, product_name, category, price
     orders   300        5 order_id, customer_id, order_date, payment_method, order_status
order_items   764        5       order_item_id, order_id, product_id, quantity, unit_price

파일 간 관계:
- customers.customer_id -> orders.customer_id
- orders.order_id -> order_items.order_id
- products.product_id -> order_items.product_id

요청:
1. 각 파일이 어떤 역할을 하는지 설명해 주세요.
2. 분석 전에 확인해야 할 항목을 체크리스트로 정리해 주세요.
3. 실제 데이터 확인 없이 단정한 내용과 추가 확인이 필요한 내용을 구분해 주세요.

## 18. LLM 답변 검증 연습

LLM이 다음과 같이 답했다고 가정해 봅니다.

> 고객 데이터에 age 컬럼이 있으므로 연령대별 매출 분석을 바로 수행하면 됩니다.

이 답변은 그럴듯하지만 충분히 안전하지 않습니다. 아래 내용을 직접 확인해야 합니다.

- `age` 컬럼이 실제로 존재하는가?
- `age` 컬럼에 결측치나 이상치가 있는가?
- 고객 데이터와 주문 데이터가 `customer_id`로 연결되는가?
- 매출을 계산하려면 주문 상세와 상품 또는 단가 정보가 필요한가?
- 취소 주문을 포함할지 제외할지 기준이 있는가?

In [45]:
validation_check = pd.DataFrame([
    {
        "question": "customers에 age 컬럼이 있는가?",
        "result": "age" in customers.columns,
    },
    {
        "question": "age 결측치 개수는?",
        "result": customers["age"].isna().sum() if "age" in customers.columns else "컬럼 없음",
    },
    {
        "question": "orders.customer_id가 customers.customer_id와 연결되는가?",
        "result": len(invalid_customers) == 0,
    },
    {
        "question": "매출 계산에 필요한 quantity와 unit_price가 있는가?",
        "result": {"quantity", "unit_price"}.issubset(order_items.columns),
    },
])

validation_check

                                            question result
0                            customers에 age 컬럼이 있는가?   True
1                                       age 결측치 개수는?      0
2  orders.customer_id가 customers.customer_id와 연결되는가?   True
3              매출 계산에 필요한 quantity와 unit_price가 있는가?   True

## 19. 이번 장 점검 체크리스트

| 점검 항목 | 확인 |
| --- | --- |
| 필요한 CSV 파일이 모두 존재하는가? | O |
| 각 데이터셋의 행과 열 개수를 확인했는가? |O|
| 컬럼명이 예상과 일치하는가? | O |
| 날짜 컬럼의 데이터 타입을 확인했는가? |O |
| 숫자 컬럼이 실제 숫자형으로 저장되어 있는가? | O |
| 결측치가 있는 컬럼을 확인했는가? |O |
| 중복 데이터가 있는지 확인했는가? | O |
| 주요 ID 컬럼의 중복 여부를 확인했는가? | O |
| 여러 파일을 연결할 키 컬럼을 확인했는가? |O|
| 파일 간 키 관계가 실제로 연결 가능한지 확인했는가? | O |
| LLM에 원본 데이터 대신 구조 요약만 입력했는가? |O |
| LLM이 제안한 설명을 실제 데이터와 비교해 검증했는가? | O |

## 20. 실습 과제

아래 과제를 직접 해결해 보세요.

1. 4개 CSV 파일의 행과 열 개수를 하나의 표로 정리하세요.
2. 각 파일의 결측치 개수와 결측치 비율을 확인하세요.
3. `orders.order_date`를 날짜 타입으로 변환하고 데이터 기간을 확인하세요.
4. `order_items`와 `products`를 병합해 카테고리별 주문 금액을 계산하세요.
5. LLM에게 데이터 구조 요약을 전달하는 프롬프트를 직접 작성하세요.
6. LLM이 만든 분석 아이디어가 실제 컬럼과 키 관계에 맞는지 검증하세요.

In [ ]:
# 과제 풀이 공간입니다.
# 필요한 코드를 직접 작성해 보세요.

In [46]:
#1. 4개 CSV 파일의 행과 열 개수를 하나의 표로 정리하세요.

shape_table = pd.DataFrame([
    {
        "dataset": name,
        "rows": df.shape[0],
        "columns": df.shape[1],
        "column_names": ", ".join(df.columns),
    }
    for name, df in datasets.items()
])

shape_table

       dataset  rows  columns                                       column_names
0    customers   150        6  customer_id, name, gender, age, city, signup_date
1     products   100        4          product_id, product_name, category, price
2       orders   300        5  order_id, customer_id, order_date, payment_met...
3  order_items   764        5  order_item_id, order_id, product_id, quantity,...

In [47]:
#각 파일의 결측치 개수와 결측치 비율을 확인하세요.
missing_table = pd.DataFrame([
    {
        "dataset": name,
        "column": col,
        "missing": df[col].isna().sum(),
        "missing_pct": round(df[col].isna().mean() * 100, 2),
    }
    for name, df in datasets.items()
    for col in df.columns
])

# 파일 단위 요약
missing_by_file = (
    missing_table.groupby("dataset", sort=False)
    .agg(total_missing=("missing", "sum"), columns_with_missing=("missing", lambda s: (s > 0).sum()))
)
missing_by_file["total_cells"] = [df.size for df in datasets.values()]
missing_by_file["missing_pct"] = (missing_by_file["total_missing"] / missing_by_file["total_cells"] * 100).round(2)

display(missing_by_file)
display(missing_table[missing_table["missing"] > 0])   # 결측치가 있는 컬럼만

             total_missing  columns_with_missing  total_cells  missing_pct
dataset
customers                0                     0          900          0.0
products                 0                     0          400          0.0
orders                   0                     0         1500          0.0
order_items              0                     0         3820          0.0

Empty DataFrame
Columns: [dataset, column, missing, missing_pct]
Index: []

In [48]:
#3. `orders.order_date`를 날짜 타입으로 변환하고 데이터 기간을 확인하세요.

orders["order_date"] = pd.to_datetime(orders["order_date"], errors="coerce")

start, end = orders["order_date"].min(), orders["order_date"].max()
print("변환 후 타입:", orders["order_date"].dtype)
print("변환 실패 건수:", orders["order_date"].isna().sum())
print("기간:", start.date(), "~", end.date(), f"({(end - start).days + 1}일)")

# 월별 주문 수 (연-월 기준)
orders["order_month"] = orders["order_date"].dt.to_period("M")
orders["order_month"].value_counts().sort_index()

변환 후 타입: datetime64[us]
변환 실패 건수: 0
기간: 2025-09-15 ~ 2026-09-14 (365일)

order_month
2025-09     9
2025-10    27
2025-11    22
2025-12    33
2026-01    29
2026-02    17
2026-03    35
2026-04    27
2026-05    28
2026-06    25
2026-07    24
2026-08    16
2026-09     8
Freq: M, Name: count, dtype: int64

In [50]:
#4. `order_items`와 `products`를 병합해 카테고리별 주문 금액을 계산하세요.
items = order_items.merge(
    products,
    on="product_id",
    how="left",
    validate="many_to_one",   # 상품 ID가 products에서 유일한지 함께 검증
)

# 병합 검증
assert len(items) == len(order_items), "병합 후 행 수가 바뀌었습니다"
print("카테고리 매칭 실패:", items["category"].isna().sum())
print("단가 ≠ 정가인 행:", (items["unit_price"] != items["price"]).sum())

items["amount"] = items["quantity"] * items["unit_price"]

category_sales = (
    items.groupby("category")
    .agg(
        order_amount=("amount", "sum"),
        quantity=("quantity", "sum"),
        item_rows=("order_item_id", "count"),
        orders=("order_id", "nunique"),
    )
    .sort_values("order_amount", ascending=False)
)
category_sales["share_pct"] = (category_sales["order_amount"] / category_sales["order_amount"].sum() * 100).round(1)

category_sales

completed_sales = (
    items.merge(orders[["order_id", "order_status"]], on="order_id", validate="many_to_one")
    .query("order_status == 'completed'")
    .groupby("category")["amount"].sum()
    .sort_values(ascending=False)
)

completed_sales

카테고리 매칭 실패: 0
단가 ≠ 정가인 행: 0

category
스포츠     31743000
전자기기    26400000
생활용품    23915000
뷰티      23383000
식품      16573000
도서      16389000
패션      10587000
Name: amount, dtype: int64

In [51]:
#5. LLM에게 데이터 구조 요약을 전달하는 프롬프트를 직접 작성하세요.

def describe_table(name, df, max_cats=10):
    lines = [f"### {name} ({df.shape[0]}행 × {df.shape[1]}열)"]
    for col in df.columns:
        s = df[col]
        info = f"- `{col}` ({s.dtype}), 결측 {s.isna().sum()}, 고유값 {s.nunique()}"
        if s.dtype == "str" or s.dtype == "object":
            if s.nunique() <= max_cats:
                info += f", 값: {sorted(s.dropna().unique().tolist())}"
        elif pd.api.types.is_datetime64_any_dtype(s):
            info += f", 범위: {s.min().date()} ~ {s.max().date()}"
        elif pd.api.types.is_numeric_dtype(s) and not col.endswith("_id"):
            info += f", 범위: {s.min()} ~ {s.max()}"
        lines.append(info)
    return "\n".join(lines)

schema_text = "\n\n".join(
    describe_table(n, d.drop(columns=["order_month"], errors="ignore"))
    for n, d in datasets.items()
)

prompt = f"""당신은 이커머스 데이터 분석가입니다. 아래 4개 테이블만 사용해 분석 아이디어를 제안하세요.

## 데이터 구조
{schema_text}

## 테이블 관계
- customers.customer_id = orders.customer_id (고객 1 : 주문 N)
- orders.order_id = order_items.order_id (주문 1 : 품목 N)
- products.product_id = order_items.product_id (상품 1 : 품목 N)
- customers와 order_items는 직접 연결되지 않으며 orders를 거쳐야 합니다.

## 참고 사항
- 금액 = order_items.quantity × order_items.unit_price
- order_status에는 completed, cancelled, refunded가 있으며, 매출은 completed만 집계합니다.
- 데이터 기간: 2025-09-15 ~ 2026-09-14 (시작·종료 월은 부분 월)

## 요청
분석 아이디어 5개를 제안하세요. 각 아이디어마다 다음을 포함하세요.
1. 분석 질문
2. 사용할 테이블과 컬럼 (위 목록에 있는 이름만 정확히 사용)
3. 필요한 join 경로
4. 집계 방법
목록에 없는 컬럼이 필요하면 "데이터에 없음"이라고 명시하세요.
"""

print(prompt)

당신은 이커머스 데이터 분석가입니다. 아래 4개 테이블만 사용해 분석 아이디어를 제안하세요.

## 데이터 구조
### customers (150행 × 6열)
- `customer_id` (int64), 결측 0, 고유값 150
- `name` (str), 결측 0, 고유값 134
- `gender` (str), 결측 0, 고유값 2, 값: ['F', 'M']
- `age` (int64), 결측 0, 고유값 48, 범위: 19 ~ 69
- `city` (str), 결측 0, 고유값 10, 값: ['고양', '광주', '대구', '대전', '부산', '서울', '성남', '수원', '울산', '인천']
- `signup_date` (str), 결측 0, 고유값 136

### products (100행 × 4열)
- `product_id` (int64), 결측 0, 고유값 100
- `product_name` (str), 결측 0, 고유값 100
- `category` (str), 결측 0, 고유값 7, 값: ['도서', '뷰티', '생활용품', '스포츠', '식품', '전자기기', '패션']
- `price` (int64), 결측 0, 고유값 80, 범위: 5000 ~ 200000

### orders (300행 × 5열)
- `order_id` (int64), 결측 0, 고유값 300
- `customer_id` (int64), 결측 0, 고유값 126
- `order_date` (datetime64[us]), 결측 0, 고유값 207, 범위: 2025-09-15 ~ 2026-09-14
- `payment_method` (str), 결측 0, 고유값 4, 값: ['bank_transfer', 'card', 'kakao_pay', 'naver_pay']
- `order_status` (str), 결측 0, 고유값 3, 값: ['cancelled', 'completed', 'refunded']

### order_items (764행 × 5열)
- `order_item_id` (int64), 결측 0, 고유값 764
- `order_id` (int64), 결측 0, 고유값 300
- `product_id` (int64), 결측 0, 고유값 100
- `quantity` (int64), 결측 0, 고유값 5, 범위: 1 ~ 5
- `unit_price` (int64), 결측 0, 고유값 80, 범위: 5000 ~ 200000

## 테이블 관계
- customers.customer_id = orders.customer_id (고객 1 : 주문 N)
- orders.order_id = order_items.order_id (주문 1 : 품목 N)
- products.product_id = order_items.product_id (상품 1 : 품목 N)
- customers와 order_items는 직접 연결되지 않으며 orders를 거쳐야 합니다.

## 참고 사항
- 금액 = order_items.quantity × order_items.unit_price
- order_status에는 completed, cancelled, refunded가 있으며, 매출은 completed만 집계합니다.
- 데이터 기간: 2025-09-15 ~ 2026-09-14 (시작·종료 월은 부분 월)

## 요청
분석 아이디어 5개를 제안하세요. 각 아이디어마다 다음을 포함하세요.
1. 분석 질문
2. 사용할 테이블과 컬럼 (위 목록에 있는 이름만 정확히 사용)
3. 필요한 join 경로
4. 집계 방법
목록에 없는 컬럼이 필요하면 "데이터에 없음"이라고 명시하세요.

In [53]:
#6. LLM이 만든 분석 아이디어가 실제 컬럼과 키 관계에 맞는지 검증하세요.
schema = {name: set(df.columns) for name, df in datasets.items()}

join_keys = {
    ("customers", "orders"): "customer_id",
    ("orders", "order_items"): "order_id",
    ("products", "order_items"): "product_id",
}

def check_idea(idea):
    issues = []
    # 1) 테이블·컬럼 존재 여부
    for table, cols in idea["columns"].items():
        if table not in schema:
            issues.append(f"없는 테이블: {table}")
            continue
        for col in cols:
            if col not in schema[table]:
                issues.append(f"{table}에 없는 컬럼: {col}")
    # 2) join 관계가 실제로 존재하는지
    for a, b in idea.get("joins", []):
        if (a, b) not in join_keys and (b, a) not in join_keys:
            issues.append(f"직접 연결 키 없음: {a} ↔ {b}")
    return issues or ["OK"]


llm_ideas = [
    {"idea": "카테고리별 완료 매출·취소율",
     "columns": {"order_items": ["order_id", "product_id", "quantity", "unit_price"],
                 "products": ["product_id", "category"], "orders": ["order_id", "order_status"]},
     "joins": [("order_items", "products"), ("order_items", "orders")]},
    {"idea": "월별 매출 추이",
     "columns": {"orders": ["order_id", "order_date", "order_status"],
                 "order_items": ["order_id", "quantity", "unit_price"]},
     "joins": [("orders", "order_items")]},
    {"idea": "지역·연령대별 구매액",
     "columns": {"customers": ["customer_id", "city", "age"],
                 "orders": ["order_id", "customer_id", "order_status"],
                 "order_items": ["order_id", "quantity", "unit_price"]},
     "joins": [("customers", "orders"), ("orders", "order_items")]},
    {"idea": "결제 수단별 취소·환불률",
     "columns": {"orders": ["payment_method", "order_status"]},
     "joins": []},
    {"idea": "재구매·첫 구매까지 기간",
     "columns": {"customers": ["customer_id", "signup_date"],
                 "orders": ["order_id", "customer_id", "order_date", "order_status"]},
     "joins": [("customers", "orders")]},
]

pd.DataFrame([{"idea": i["idea"], "result": "; ".join(check_idea(i))} for i in llm_ideas])

              idea result
0  카테고리별 완료 매출·취소율     OK
1         월별 매출 추이     OK
2      지역·연령대별 구매액     OK
3    결제 수단별 취소·환불률     OK
4    재구매·첫 구매까지 기간     OK

## 마무리

이번 장의 핵심은 “데이터를 불러왔다”에서 끝내지 않는 것입니다.

데이터 분석을 시작하기 전에 파일, 행과 열, 컬럼명, 데이터 타입, 결측치, 중복, 키 관계를 확인해야 이후 분석이 흔들리지 않습니다. 다음 장에서는 이 구조를 바탕으로 pandas의 선택, 필터링, 정렬, 집계 기초를 다룹니다.